In [1]:
prices = []
N = 60*60*24*365
for i in range(N):
    prices.append(100 + i/100)
print(prices[:5])

[100.0, 100.01, 100.02, 100.03, 100.04]


In [2]:
avg = 0.0
for p in prices:
    avg += p/len(prices)
print(avg)

157779.995


In [3]:
import numpy as np

In [5]:
prices = 100 + np.arange(N)/100
print(prices[:5])

[100.   100.01 100.02 100.03 100.04]


In [6]:
avg = np.mean(prices)
print(avg)

157779.995


In [7]:
arr = np.array([10,20,30,40,50])

In [8]:
print(arr)

[10 20 30 40 50]


In [9]:
arr.ndim

1

In [10]:
arr.shape

(5,)

In [11]:
len(arr)

5

In [12]:
arr_2d = np.array([[10,20,30,40,50],[100,200,300,400,500]])

In [13]:
print(arr_2d)

[[ 10  20  30  40  50]
 [100 200 300 400 500]]


In [14]:
arr_2d.ndim

2

In [15]:
arr_2d.shape

(2, 5)

In [16]:
len(arr_2d)

2

In [17]:
arr_2d.size

10

In [18]:
type(arr_2d)

numpy.ndarray

In [19]:
arr_2d.dtype

dtype('int32')

In [20]:
np.zeros(shape=3)

array([0., 0., 0.])

In [21]:
np.zeros(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])